version: "2.3"

services:
  jupyterlab:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./notebooks:/notebooks
    ports:
      - 8989:8989
    environment:
      JUPYTER_PASSWD: jupyter
      JUPYTER_PORT: 8989