version: "2.3"

services:
  evcxr:
    build:
      context: .
      dockerfile: Dockerfile
    user: 1000:1000
    volumes:
      - ./notebooks:/notebooks
      - ./config:/config
    ports:
      - 8888:8888
    environment:
      JUPYTER_PASSWD: jupyter